### ISSUE TITLE
Consider renaming this project to not include the PEP number

### ISSUE THREAD

**Issue by pradyunsg** [FFY00/python-pyproject-metadata#10]
We've already made this mistake once with `pep517` and I'd really like it if we as a community can avoid doing that again with this project.

`pep517` is realistically a package for providing wrappers for hooks that were initially specified in PEP 517. Those have since been expanded, most recently in PEP 660 and now the project name does not make as much sense. We also made the same mistake in pip's CLI -- using the PEP name rather than a user-friendly concept name.

Let's use a more user-friendly name here, that better conveys the purpose of this package?

**Comment by FFY00** [comment]
That makes sense, what name do you propose?

When I released this, I did not intend it to be a round for a long time, as I hope this functionality will eventually be provided by https://github.com/pypa/packaging. I just created this package because I was developing a few different build backends and wanted to reuse the code, so I just extracted it to a separate package.
I am fine keeping supporting this, but I hope https://github.com/pypa/packaging will provide metadata handling soon(-ish).

**Comment by pradyunsg** [comment]
https://pypi.org/project/pyproject-metadata?

**Comment by FFY00** [comment]
@pradyunsg that sounds good? Could you either delete the PyPI project or add me as a maintainer?

**Comment by pradyunsg** [comment]
You should've gotten an invite. :)

**Comment by FFY00** [comment]
@pradyunsg I don't think I ever got an invite. I would like to make a release soon, could you look into that?

**Comment by pradyunsg** [comment]
I’d certainly sent an invite, which the PyPI UI states had expired. Sent another invite!

**Comment by pradyunsg** [comment]
There’s a 24 hour expiry on the invite, IIRC.
