### ISSUE TITLE
BUG: failure in SciPy build with version bounds

### ISSUE THREAD

**Issue by tylerjereddy** [FFY00/python-pyproject-metadata#22]
For details see: https://github.com/scipy/scipy/pull/16353#issuecomment-1151711888

It is reproduced in the CI there as well. Happens with `0.4.0.post1` but not the previous `0.4.0`.

**Comment by tylerjereddy** [comment]
Ah, this may be "ok" when a new version of `meson-python` gets released though based on my testing of https://github.com/FFY00/meson-python/pull/77/ 

Though this is getting a bit confusing in terms of which versions are allowed with which..

**Comment by rgommers** [comment]
> Though this is getting a bit confusing in terms of which versions are allowed with which..

Yes, that's a generic issue with transitive dependencies. I think it's fine for now, while things are new. In the longer term we should see if things are stable or not. Pip vendors other packaging components rather than depend on them (see [src/pip/_vendor](https://github.com/pypa/pip/tree/main/src/pip/_vendor)), which can be a better alternative (it certainly is for Pip I'd say) - but it's extra work of course.

> Happens with `0.4.0.post1` but not the previous `0.4.0`.

I think this was explained elsewhere already as `0.4.0.post1` contents being wrong because it was released from the wrong branch.

**Comment by FFY00** [comment]
Yup, this was an issue with the `pep621` dependency. It should be fixed now.
