### ISSUE TITLE
version must not be automatically set to dynamic if `[project]` table is present

### ISSUE THREAD

**Issue by rgommers** [FFY00/python-pyproject-metadata#67]
As discussed in https://github.com/mesonbuild/meson-python/issues/454 and specified in https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata, the `version` field is a required field of the `[project]` table; it _must_ be specified either statically or listed as dynamic.

Furthermore, that spec says _"No tools may add keys to this table which are not defined by this specification"_. Hence `pyproject-metadata` is not allowed to automatically fill in this field. That it's doing so is probably an oversight.

**Comment by henryiii** [comment]
This is going to be tricky to fully fix (also wanting to generalize to all fields). The problem is that pyproject-metadata is trying to auto-compute Metadata 2.2 dynamic _from_ dynamic, which is incorrect. Just because an author specifies a value in `dynamic` does not say anything about the behavior between SDist and wheel, which is what Metadata 2.2 dynamic is about.

I think the long term fix might be as follows: add two new fields. `value_added` and `build_dynamic`. Whenever a user sets a value, `value_added` records it. Then we can compute `set(dynamic) - set(value_added)` and if anything is left, throw an error if metadata is requested. A user would have to manually set `build_dynamic`, which would trigger Metadata 2.2 and that list would be populated in the dynamic field.
